name: Generate Pacman

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          npm install -g @octokit/rest
          npm install -g svgo
      - name: Generate Pacman graph
        run: |
          mkdir -p dist
          node -e "
            const { Octokit } = require('@octokit/rest');
            const fs = require('fs');
            const path = require('path');
            
            const octokit = new Octokit({
              auth: process.env.GITHUB_TOKEN
            });
            
            async function getContributions() {
              try {
                const response = await octokit.request('GET /repos/{owner}/{repo}/contributors', {
                  owner: 'ELMACHHOUNE',
                  repo: 'ELMACHHOUNE'
                });
                
                return response.data;
              } catch (error) {
                console.error('Error fetching contributions:', error);
                return [];
              }
            }
            
            async function generatePacmanGraph() {
              const contributions = await getContributions();
              
              // Create SVG content
              let svgContent = '<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"100%\" height=\"100%\" viewBox=\"0 0 800 400\">';
              
              // Add Pacman
              svgContent += '<circle cx=\"400\" cy=\"200\" r=\"150\" fill=\"#FFD700\" />';
              svgContent += '<path d=\"M400,200 L550,200 A150,150 0 0,0 400,50 Z\" fill=\"#000\" />';
              
              // Add contribution dots
              let x = 50;
              contributions.forEach((contrib, index) => {
                const y = 50 + (index % 10) * 30;
                const size = Math.min(20, contrib.contributions / 10 + 5);
                svgContent += `<circle cx=\"${x}\" cy=\"${y}\" r=\"${size}\" fill=\"#4CAF50\" />`;
                if ((index + 1) % 10 === 0) x += 30;
              });
              
              svgContent += '</svg>';
              
              // Write to file
              fs.writeFileSync(path.join('dist', 'pacman-contribution-graph.svg'), svgContent);
              
              // Create dark version
              const darkSvgContent = svgContent.replace('#FFD700', '#FFA500').replace('#4CAF50', '#8BC34A');
              fs.writeFileSync(path.join('dist', 'pacman-contribution-graph-dark.svg'), darkSvgContent);
              
              console.log('Pacman graph generated successfully!');
            }
            
            generatePacmanGraph();
          "
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
