name: Generate Pacman

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jstnm/pacman-contribution-graph@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: ELMACHHOUNE
          output_path: dist/pacman-contribution-graph.svg
          dark_output_path: dist/pacman-contribution-graph-dark.svg
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
